### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by pr1smo**

### CODE REVIEW

**Comment by pr1smo** [comment]
this is for my flatiron prep course

**Comment by chrisdavidmills** [comment]
I'm sorry, but you can't just make unneeded changes to our repos and have them accepted. What do you want to achieve here? If you need to make a commit to some kind of open source project, I can probably find you something to do.

**Comment by pr1smo** [comment]
I'm sorry, I don't really understand GitHub, I didn't mean to.

**Comment by pr1smo** [comment]
I was trying to make it work in the for me, but it didn't. Won't do it again.

**Comment by chrisdavidmills** [comment]
Hey, don't worry — it is OK.

**Pull request closed without merging**
