### PR TITLE
Update JS "Objects" module to use modern JS features

### PR DESCRIPTION
**Pull request by wbamberg**
Part of https://github.com/mdn/content/issues/10337.

This is the learning-area companion to https://github.com/mdn/content/pull/11373. I won't describe what it does in detail because it really matches the updates in https://github.com/mdn/content/pull/11373, as described in https://github.com/mdn/content/pull/11373#issue-1086068713 and https://github.com/mdn/content/pull/11373#issuecomment-1005997741.

This PR ought to be merged at about the same time as the mdn/content PR, and any changes made to each should be reflected in the other. For that reason I'm setting this to draft until both PRs are approved.

### CODE REVIEW

**Review by Rumyra — APPROVED** [review]

**Comment by Rumyra** [comment]
This all looks good to me 👍

**Review by Elchi3 — COMMENTED** [review]
"Object basics" reviewed. Looks great, just a nit.

**Review by Elchi3 — COMMENTED** [review]
Are javascript/oojs/tasks/oojs/oojs2.html and javascript/oojs/tasks/oojs/oojs2-download.html missing from this PR?

Edit: Oh, I see the files are there so I guess they are just empty starting points. Never mind then.

**Review by Elchi3 — APPROVED** [review]
Amazing work, Will! I think this good to go modulo the one suggestion that I made (you only applied one of the two apparently?).

**Review by Rumyra — APPROVED** [review]

**Pull request merged**
