### PR TITLE
fix: standardize lang attribute usage in HTML tutorial on MDN to 'en-US'

### PR DESCRIPTION
**Pull request by luv2027**
fixes: #672

This PR standardize the lang attribute usage in HTML tutorial to 'en-us'

Screenshot 2023-10-26 230149

### CODE REVIEW

**Comment by kuthathwe** [comment]
Good :)

**Review by caugner — CHANGES_REQUESTED** [review]
Thank you for your contribution.

According to https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang, the region part of the locale should be uppercase. Can you update all the lang values to `en-US`? 🙏

**Review by bsmth — APPROVED** [review]
Thank you! Waiting for Claas to have a look, too

**Review by caugner — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
