### PR TITLE
Update advanced-text2.html - fix typo

### PR DESCRIPTION
**Pull request by RafaelGreen1**
change H20 to H2O

### CODE REVIEW

**Comment by RafaelGreen1** [comment]
@TomoiagaPaul

**Review by chrisdavidmills — APPROVED** [review]
Good spot, thanks @RafaelGreen1 !

Weird, as someone else tried to change the O's to 0's somewhere else, and I didn't accept the PR. Maybe I meged it by accident...?

**Comment by RafaelGreen1** [comment]
there are no changes like you say in the history of the file
image
by the way I have to also update the download file, I'll do it soon

**Comment by chrisdavidmills** [comment]
>  by the way I have to also update the download file, I'll do it soon

great, thanks, much appreciated!

**Pull request merged**
