### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by abhkt2611**

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
This addition doesn't add anything to the example; in fact it makes it look worse.

**Comment by abhkt2611** [comment]
It will not repeat ,I'm a beginner and i was checking how to contribute. 
can you tell me that what type of things we can add ?

**Comment by chrisdavidmills** [comment]
I don't really want you to make additions to the existing examples in this repo — they are set up in a  specific way to teach specific things.

If you want to contribute, a good way to do it would be to drop us a message on https://discourse.mozilla-community.org/t/learning-web-development-marking-guides-and-questions/16294/6, and we can discuss what you want to do.

Best regards,

Chris

**Comment by abhkt2611** [comment]
OK Sir ,so from where i can start contribution

**Comment by chrisdavidmills** [comment]
Send me an e-mail at cmills at mozilla dot com, and tell me what you want to do, to contribute.

**Pull request closed without merging**
