### PR TITLE
Improved Code Readability

### PR DESCRIPTION
**Pull request by clintonyeb**
Wish to contribute to the MDN Guide. Please take a look and provide me with feedback. Thank you.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Yup, this looks like a nice improvement to the code. Thanks!

**Comment by clintonyeb** [comment]
I also changed the code from the website directly. Hope I didn't mess up :face_with_head_bandage:

**Comment by chrisdavidmills** [comment]
Nope, you did great. I checked your changes there too ;-)

**Comment by clintonyeb** [comment]
Just completed the checkbox hack

`input[type="checkbox"] {
  position: absolute;
  top: -100px;
}`

I think it will be better to just set display: none
`input[type="checkbox"] {
  display: none;
}`

Then it wont interfere with page layout at all, even on mobile. Just saying though :smile:

**Comment by chrisdavidmills** [comment]
Yup, we could do that. Although I tend to advocate against using display: none, as the contents are completely invisible to screenreaders.

In this case it doesn't make a huge difference, as the checkbox is being used somewhat unsemantically, which brings it's own problems. BUT - I still like to not encourage use of display: none; for hiding content that still needs to be detectable.

**Comment by clintonyeb** [comment]
Okay thanks. Its' well noted. 
You will be hearing from me again, hopefully. I'm vacations and I want to master HTML, CSS and JavaScript before next semester. The Guides are too good. No need to buy a book. Thanks for such great work. And I see your picture everywhere! Damn, you must be hardworking :smile:

**Comment by chrisdavidmills** [comment]
I do try - it's taken me about 15 months on and off to write the learning area tutorials ;-)

I am really glad you are finding them useful, and also glad that you are diving in and helping to make improvements ;-)

Good luck with your studies, and let me know if you have any more questions.

**Pull request merged**
