### PR TITLE
Update oojs-finished.html

### PR DESCRIPTION
**Pull request by MarckK**

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Hi there,

I've seen all of the edits you've made to the object basics article.

They look correct, but there is an issue here — all the modern ES stuff you've put in hasn't been explained anywhere previously in the course, so currently it doesn't really work. 

I was intending to run a project slightly later on this year to update it all. Would you like to be part of that?

For now, I'm probably going to have to revert your work because it makes the course kind not make sense.

**Comment by MarckK** [comment]
Hi Chris,

Thank you for your email.

I completely understand that you can't use what I've done if it doesn't fit
within a larger course structure. I had chanced upon the page, so wasn't
really aware of its position within a larger course context.

Yes, I'd be happy to be involved in updating the tutorials! Just let me
know when you are planning to do so.

MDN Web Docs have been hugely helpful to me, so I'm really happy to give
back. :)

Kind regards,
Kara

**Comment by chrisdavidmills** [comment]
Thanks Kara,

I really appreciate your understanding, and offer of help.

Ultimately, this code update will probably be of use to us later on, so I'll leave this PR open for now. I'll be in touch when I get this project up and running.

**Comment by chrisdavidmills** [comment]
Hi @MarckK , it's been a long time. But I think we are now ready for this work to commence, so I've merged your PR. Are you still willing to help on this? ;-)

**Comment by MarckK** [comment]
Hi @chrisdavidmills! I would be really pleased to keep contributing to this. :) Is there another channel of communication, that I should join, where this project is discussed?

**Comment by chrisdavidmills** [comment]
Well, I guess the best thing to do would be to work through all the MDN JavaScript articles sequentially, changing var to let/const as appropriate, then updating the accompanying code examples, then giving them to me to review. 

There is no rush on these; you can work through them at your own pace.

Start by going to https://developer.mozilla.org/en-US/docs/Learn/JavaScript, then keep doing them at your own pace. There is no rush,and you can do them at your own pace.

If you want to discuss them over mail, feel free to email me at cmills [at] mozilla [dot] com

**Comment by MarckK** [comment]
Great; thank you, Chris! We can continue further discussion by email, if needed. 😄

**Pull request merged**
