### PR TITLE
update css-and-js.html

### PR DESCRIPTION
**Pull request by pr1smo**
I can't get this to open up the way that it is supposed to on my browser. I don't know what I'm doing wrong.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
What exactly is not working for you with this example? I've just tried it as it currently is in the repo, and it seems to still work fine.

**Comment by pr1smo** [comment]
Either the CSS will work or the JavaScript will work but they don't work together. When the CSS is active I can't create a list but if the CSS isn't active I can. I don't know what I'm doing wrong. I've since moved on in the Mozilla course and all the other things I do work as they should.

**Comment by chrisdavidmills** [comment]
OK, no problem then. I think that if other examples are working fine, then you should not worry about this. Probably some kind of subtle syntax error ;-)

**Comment by chrisdavidmills** [comment]
By the way, if you have questions about something to do with an example in this repo, but you are not sure if something should be changed, you can file an issue instead of a pull request. See the "Issues" tab at the top of the repo.

**Pull request closed without merging**
