### PR TITLE
rm x-ua-compatible

### PR DESCRIPTION
**Pull request by wbamberg**
Fixes https://github.com/mdn/content/issues/26623.

According to [our own docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#http-equiv):

> x-ua-compatible: If specified, the content attribute must have the value "IE=edge". User agents are required to ignore this pragma.  

Some of the usages here were incorrect and giving validator errors. I think it's best to remove it everywhere.

This PR is in 2 commits:

* https://github.com/mdn/learning-area/commit/adde4d181696908c978d57f4756a9bf0efeb109c: Prettier noise
* https://github.com/mdn/learning-area/commit/c1a0cb863cee00d36ec043a13ddc6ef512ff804c: substantive changes

@teoli2003 , can you review?

### CODE REVIEW

**Comment by Josh-Cena** [comment]
O no... If we do care about validators (or at least not letting the validator confuse learners) the trailing slashes here are surely going to be problematic.

**Comment by wbamberg** [comment]
> O no... If we do care about validators (or at least not letting the validator confuse learners) the trailing slashes here are surely going to be problematic.

If you're talking about the trailing slashes Prettier adds, then:
- we've already had this conversation and decided apparently that we will accept Prettier here. I don't personally agree but don't see why we want to have this conversation again.
- the validation generates an info message for the trailing slashes, not an error

**Comment by Josh-Cena** [comment]
Thanks. In general I've been saddened by Prettier's behavior on HTML, but it seems okay here.

**Review by teoli2003 — APPROVED** [review]
👍

**Comment by teoli2003** [comment]
I'm happy to see `X-UA-Compatible` go. I always hated it (and there are not many things I hate). 

For Prettier, I love it with JS, mostly like it with CSS (there are a few oddities), and don't like it for HTML. One day we'll find an alternative (a Prettier-for-docs ?): it is not irreversible.

**Pull request merged**
