### PR TITLE
events2 exercise: Without tabIndex the canvas can't get focus

### PR DESCRIPTION
**Pull request by KjellKod**
Without tabIndex the canvas can't get focus and the exercise won't work, without adding exactly this within the HTML area which is  above `// add your code here`

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@KjellKod You can complete this example without needing to focus the canvas if you use a `key*` event on the `window` object rather than on the `<canvas>` element, but I think this addition is still a good one — it increases the reader's options for how they can complete the assessment, and makes keyboard a11y somewhat better.

Can you also make this change to the `<canvas>` element in the events2.html file too?

Many thanks.

**Comment by KjellKod** [comment]
Sure thing

**Comment by KjellKod** [comment]
@chrisdavidmills the PR is updated

**Comment by chrisdavidmills** [comment]
Perfect; thanks!

**Pull request merged**
