### PR TITLE
Create oojs.html

### PR DESCRIPTION
**Pull request by TheCodePilot**
The <script></script> element should be inside the <body>, or in the <head>

### CODE REVIEW

**Comment by TheCodePilot** [comment]
Fehler

**Review by bsmth — APPROVED** [review]
Thanks @TheCodePilot on your contribution, well done! 🙌🏻

If you want to have a look for other tasks, we have a [contributor board](https://github.com/orgs/mdn/projects/25). Issues labeled with `good first issue` are a great place to start. You can find out more information here: https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Getting_started

**Comment by teoli2003** [comment]
I think this is wrong. The `<script>` element must be in the `<head>` not in the `<body>`.

**Comment by TheCodePilot** [comment]
Ok, I'll check it out. The result: It is often seen in the <head>, but both
<body> or <head> are possible.
Tested with Visual Studio 2023.

greetings

Am Fr., 24. Feb. 2023 um 11:22 Uhr schrieb Jean-Yves Perrier <
***@***.***>:

**Comment by teoli2003** [comment]
Sorry, I removed the message as I was wrong.

**Comment by TheCodePilot** [comment]
No problem, thanks!

Am Fr., 24. Feb. 2023 um 13:32 Uhr schrieb Jean-Yves Perrier <
***@***.***>:

**Pull request merged**
