### PR TITLE
Move <script> tag before the closing </body>.

### PR DESCRIPTION
**Pull request by psylone**
According to [the article](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#Applying_CSS_and_JavaScript_to_HTML):

> The <script> element does not have to go in the head; in fact, often it is better to put it at the bottom of the document body (just _before_ the closing &lt;/body&gt; tag), to make sure that all the HTML content has been read by the browser before it tries to apply JavaScript to it (if JavaScript tries to access an element that doesn't yet exist, the browser will throw an error.)

Also, with the `<script>` after the closing `</body>` we'll not pass W3C validation:

<details>
  <summary>W3C validation result</summary>
  
</details><br>

Not sure, can we safely move all `<script>` tags before the closing `</body>` in all other cases in the repo.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Thanks for spotting this. Yes, the <script> elements should all be inside the </body>, not after it. Do you fancy updating your PR to fix all of these?

**Comment by chrisdavidmills** [comment]
Well, all the ones you have found ;-)

**Comment by psylone** [comment]
Sure!

**Comment by psylone** [comment]
Found the rest cases with regexp, that should be fine now )

**Comment by chrisdavidmills** [comment]
Awesome, thanks! I've also gone through and made any necessary changes to the articles.

**Pull request merged**
